# Generated by Django 4.1.5 on 2023-01-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('cover', models.ImageField(upload_to='groups/photos', verbose_name='Обложка')),
                ('created_at', models.DateField(verbose_name='Создана в:')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
