# Generated by Django 4.1.5 on 2023-01-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='fit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fit.fit', verbose_name='Фиты'),
            preserve_default=False,
        ),
    ]
