# Generated by Django 4.1.5 on 2023-01-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email addres')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='users/photos', verbose_name='Фото')),
                ('bio', models.TextField(max_length=255, verbose_name='Биография')),
                ('is_active', models.BooleanField(default=False, verbose_name='')),
                ('is_staff', models.BooleanField(default=False, verbose_name='')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
