# Generated by Django 4.1.5 on 2023-01-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0002_alter_artist_date_of_birth_alter_artist_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('audio_file', models.FileField(upload_to='albums/audios', verbose_name='Аудиофайл')),
                ('cover', models.ImageField(upload_to='albums/covers', verbose_name='Обложка')),
                ('realised_at', models.DateField(verbose_name='Выпушен')),
                ('artist', models.ManyToManyField(related_name='album', to='artist.artist', verbose_name='Исполнители')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
    ]
