# Generated by Django 4.1.5 on 2023-01-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_fit'),
        ('album', '0002_album_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(related_name='album', to='song.song', verbose_name='Песни'),
        ),
    ]
