# Generated by Django 4.1.5 on 2023-01-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_description_alter_group_title'),
        ('artist', '0002_alter_artist_date_of_birth_alter_artist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='group.group', verbose_name='Группы'),
            preserve_default=False,
        ),
    ]
