# Generated by Django 4.1.5 on 2023-01-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist_group'),
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fit',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='Песня'),
            preserve_default=False,
        ),
    ]
